### PR TITLE
Fix LaTeX

### PR DESCRIPTION
**Pull request by flcl42**
One more little change needed after previous two requests merged. Escapes markdown _italic_ modifier

### CODE REVIEW

**Comment by flcl42** [comment]
Plz don't merge berfre #33, I'll add the same fix for those changes

**Comment by CarlBeek** [comment]
It's frustrating that GitHub's markdown + latex/mathtex/mathjax pipeline breaks like this. It especially bothers me as I render these all locally and they are fine, it is just here online that they are broken. :/

I'll hold off here until #33 is merged as requested. Could you take a look at https://github.com/ethereum/kzg-ceremony-specs/blob/master/docs/sequencer/sequencer.md#pairing-checks too please.

**Comment by CarlBeek** [comment]
#33 is merged!

**Comment by flcl42** [comment]
@CarlBeek Yep, the risk is that it may render differently outside of github.

**Comment by asanso** [comment]
> Plz don't merge berfre https://github.com/ethereum/kzg-ceremony-specs/pull/33, I'll add the same fix for those changes

https://github.com/ethereum/kzg-ceremony-specs/pull/33 is now merged it might be useful to merge this as well now

**Pull request merged**
